---
title: "Introduction to Balanced Teams"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to Balanced Teams}
  %\VignetteDepends{dplyr}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r opts, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(balancedteams)
library(dplyr)
```

```{r aux_function, echo = FALSE}
GetMeanScore <- function(df) {
  out <- dplyr::group_by(df, team_id) %>% 
  dplyr::summarize(`Mean Score` = mean(score),
            `# Groups` = dplyr::n()) %>% 
  dplyr::arrange(team_id)
  
  return(out)
}
```

```{r data}
head(mens_team)
```

```{r greedy_7}
team_config_one <- GenerateBalancedTeams(mens_team, 
                                         num_teams = 7)
GetMeanScore(team_config_one)
```

```{r greedy_7_2}
team_config_two <- GenerateBalancedTeams(mens_team, 
                                         num_teams = 7)
GetMeanScore(team_config_two)
```

```{r greedy_6}
team_config_three <- GenerateBalancedTeams(mens_team, 
                                           num_teams = 6)
GetMeanScore(team_config_three)
```

```{r MILP}
team_config_four <- GenerateBalancedTeams(mens_team, 
                                          num_teams = 7,
                                          method = "MILP")
GetMeanScore(team_config_four)
```
